### ISSUE TITLE
Allow copy output panel texts.

### ISSUE THREAD

**Issue by xpol** [noseglid/atom-build#221]
Currently cmd+c will not work.

**Comment by noseglid** [comment]
This used to be an issue, reported and fixed in #34. It seems to have stopped working again though. I have confirmed that the fix in #34 is still in place. Something else must've changed. Thanks for reporting.

**Comment by noseglid** [comment]
This probably is a regression in Atom: https://github.com/atom/atom/issues/9548 I'll keep tabs on it and push to get it resolved.

**Comment by ebkalderon** [comment]
Seems to work fine on my Arch box. It seems like atom/atom#9548 has been fixed. Can we close this issue now?

**Comment by xpol** [comment]
@ebkalderon What version of Atom do you use? I use 1.2.3 and not fixed.

**Comment by noseglid** [comment]
This works for me on the Beta channel (shasum atom/atom@f159e81), which suggests it will be fixed in `1.3.0`.

I want to keep this open until it is fixed in stable.

**Comment by xpol** [comment]
1.3.0 has released.
Tested on mac, still can not copy via `cmd-c`.

**Comment by noseglid** [comment]
Still not fixed. Apparently not included in `1.3.0` until 1.4.0. I'm trying to push for a minor release to get this fixed sooner.

In Beta channel this works.

**Comment by xpol** [comment]
Finally, the Atom releases `1.3.1` and fixes this.
@noseglid Thanks!

**Comment by noseglid** [comment]
Yea. looks like it works now. Great that we managed to get a point release for this. This has been open for too long.
